# Generated by Django 4.1.3 on 2022-11-21 03:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_name', models.CharField(max_length=20)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_concat', models.CharField(max_length=20)),
                ('emp_role', models.CharField(max_length=50)),
                ('emp_salary', models.IntegerField()),
                ('id', models.UUIDField(default=uuid.UUID('021586d2-a1b8-46e4-bf4c-360321ad741d'), editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
