# Generated by Django 4.1.3 on 2022-11-21 03:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a8978ed0-cf97-486b-9539-94aa3d035174'), editable=False, primary_key=True, serialize=False),
        ),
    ]
