# Generated by Django 4.1.3 on 2022-11-21 04:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f3853f80-de71-458a-a329-4ed4e119354a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
