# Generated by Django 4.1.3 on 2022-11-21 07:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_concat',
            new_name='emp_contact',
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a7b022cb-5a11-43b5-b8e6-6d60341611c8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
