# Generated by Django 4.1.3 on 2022-11-21 07:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_emp_concat_employee_emp_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('670e49bd-22ba-4dc4-9c37-4c66d140c2d7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
